import React, { useEffect, useState } from "react";
import { Loader, Card, FormField } from "../components/index";
const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} />);
  }
  return (
    <h2 className="mt-5 font-bold text-[#6449ff] text-xl uppercase">{title}</h2>
  );
};
const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);
  const [searchText, setSearchText] = useState("");
  const [searchResults, setSearchResults] = useState(null);
  const [searchTimeout, setSearchTimeout] = useState(null);
  const handleSearchChange = (e) => {
    clearTimeout(searchTimeout);
    setSearchText(e.target.value);
    setSearchTimeout(
      setTimeout(() => {
        const searchResult = allPosts.filter(
          (item) =>
            item.prompt.toLowerCase().includes(searchText.toLowerCase()) ||
            item.name.toLowerCase().includes(searchText.toLowerCase())
        );
        setSearchResults(searchResult);
      }, 1000)
    );
  };
  useEffect(() => {
    const fetchPost = async () => {
      setLoading(true);

      try {
        const response = await fetch(
          "https://aiimage-fqdx.onrender.com/api/v1/post",
          {
            method: "GET",
            headers: {
              "content-Type": "application/json",
            },
          }
        );
        if (response.ok) {
          const results = await response.json();
          setAllPosts(results.data.reverse());
        }
      } catch (error) {
        alert(error.message);
      } finally {
        setLoading(false);
      }
    };
    fetchPost();
  }, []);
  return (
    <section>
      <div className="max-w-7xl ">
        <div>
          <h1 className="font-extrabold text-[#222328] text-[32px]">
            The Community Showcase
          </h1>
          <p className="mt-2 text-[#666e75] text-[16px] max-w-[500px]">
            Browser Through a collection of imaginative and visually stunning
            images generated by DALL-E AI
          </p>
        </div>
      </div>
      <div className="mt-16">
        <FormField
          labelName="Search Post"
          type="text"
          name="text"
          placeholder="Search Post"
          value={searchText}
          handleChange={handleSearchChange}
        />
      </div>
      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-[#666e75] text-xl mb-3">
                Showing results for
                <span className="text-[#222328]"> {searchText}</span>
              </h2>
            )}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-11 gap-3">
              {searchText ? (
                <RenderCards
                  data={searchResults}
                  title="No Search Result found"
                />
              ) : (
                <RenderCards data={allPosts} title="No Post found" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
